### PR TITLE
80 discrepancy of simulation budget and actual simulation attempts

### LINKED ISSUE #80: Discrepancy of simulation_budget and actual simulation attempts
## Description

The number of simulations does not match the selected budget, as sampling of initial population is not counted towards the budget.

## Suggested Changes to evobandits.rs

* Count initial population towards the budget. As a shortcut, we could modify `let mut simulation_used: usize = 0;` to match the specified budget exaclty.
* A simulation budget of 0, and budgets that are smaller than the population size should should raise an Exception.

## Python Example

```python
from evobandits import EvoBandits

evaluation_count = 0

def rosenbrock_function(number: list):
    global evaluation_count
    evaluation_count += 1
    return sum(
        [
            100 * (number[i + 1] - number[i] ** 2) ** 2 + (1 - number[i]) ** 2
            for i in range(len(number) - 1)
        ]
    )


if __name__ == "__main__":
    bounds = [(-5, 10), (-5, 10)]

    # A value of 0 should raise an Exception
    evaluation_budget = 0

    evobandits = EvoBandits(population_size=20)
    result = evobandits.optimize(rosenbrock_function, bounds, evaluation_budget)
    
    print("Evaluation Budget: ", evaluation_budget)
    print("Actual evaluation count: ", evaluation_count)
    print(result)

```
```
Evaluation Budget:  0
Actual evaluation count:  21
[2, 6]
```

### PR DESCRIPTION
**Pull request by fwuermseher**
This PR aims to close #80 by counting the sampling of the initial population towards the budget. 
 
Additionally, fixed an edge case: one arm was pulled "over budget" if simulation budget == population size.

### Example for the Edge Case (fixed with second commit)

```python
from evobandits import EvoBandits

evaluation_count = 0

def rosenbrock_function(number: list):
    global evaluation_count
    evaluation_count += 1
    return sum(
        [
            100 * (number[i + 1] - number[i] ** 2) ** 2 + (1 - number[i]) ** 2
            for i in range(len(number) - 1)
        ]
    )


if __name__ == "__main__":
    bounds = [(-5, 10), (-5, 10)]

    # Edge case: if evaluation budget = population size, one more simulation is used
    evaluation_budget = 20

    evobandits = EvoBandits(population_size=20)
    result = evobandits.optimize(rosenbrock_function, bounds, evaluation_budget)
    
    print("Evaluation Budget: ", evaluation_budget)
    print("Actual evaluation count: ", evaluation_count)
    print(result)
```
```
Evaluation Budget:  20
Actual evaluation count:  21
```

### CODE REVIEW

File: evobandits/src/evobandits.rs [hunk 1]
```diff
@@ -158,13 +158,20 @@ impl EvoBandits {
         self.genetic_algorithm.set_bounds(bounds);
         self.genetic_algorithm.validate();
 
+        if simulation_budget < self.genetic_algorithm.population_size {
+            panic!(
+                "simulation_budget must be at least population_size ({})",
+                self.genetic_algorithm.population_size
+            );
+        }
```
Comment (tnkuehne) [inline evobandits/src/evobandits.rs:166]:
```suggestion
        assert!(
            simulation_budget >= self.genetic_algorithm.population_size,
            "simulation_budget must be at least population_size ({})",
            self.genetic_algorithm.population_size
        );
```
Wouldn't this be semantically nicer?

Comment (fwuermseher) [reply evobandits/src/evobandits.rs:166]: Yes. Did not think about that because [Python assertions can be bypassed](https://stackoverflow.com/questions/61826628/what-is-the-advantage-if-any-of-using-assert-over-an-if-else-condition) which means I tend to avoid them. [Rust's assert statement](https://doc.rust-lang.org/std/macro.assert.html) is safe though.

**Review by tnkuehne — APPROVED** [review]
